name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Get paket
      run: |
        cd DataProvider
        dotnet tool restore
        dotnet paket update
    - name: Build and test
      run: |
        dotnet build -c release
        dotnet test -c release
    - name: Build NuGet package with paket
      run: |
        cd DataProvider
        dotnet paket pack nuget
