// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DataProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("DataProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing DataProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DataProvider.Runtime"
    let [<Literal>] AssemblyProduct = "DataProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing DataProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
